### ISSUE TITLE
No results retrieved by EPA after simulation is run - status: ERROR

### ISSUE THREAD

**Issue by smartie2076** [rl-institut/mvs_eland_api#10]
There are some examples of energy systems that can be sent to the MVS (no `500 Error`), but then no results are received by the EPA and an `ERROR` is displayed in the status bar. There is an energy system in the `testUser` account that runs through, so we need to figure out where the issue arises - at EPA side when parsing the inputs, when reading into the MVS, parsing the MVS results into EPA format or on EPA side when parsing the results.

Examples of energy systems in account `martha.hoffmann`:

- Energy system with just a demand and an energy provider - [Scenario "Only demand and provider"](https://epa-eland.rl-institut.de/scenario/search/2)
- Simple energy system - [Scenario "PV, Demand, Provider"](https://epa-eland.rl-institut.de/scenario/search/2)
- Real-life energy system (no real data) - [Scenario "Simplified 2"](https://epa-eland.rl-institut.de/scenario/search/3)

Todos:
- [x] Post screenshots of "network analysis" when executing a simulation
- [x] Retrieve input data from the "network analysis" for all three scenarios, create json files from it
- [x] Read the inputs with the EPA-MVS parser and try to execute simulation
- [x] Post error messages, if any

**Comment by smartie2076** [comment]
### Screenshots of executing simulation
Executing the simulation - here we can fetch the data sent to the MVS.
![grafik](https://user-images.githubusercontent.com/44204527/109017875-dd5ec380-76b7-11eb-8002-7355c9daac93.png)

One has to reload to be able to see the status update:

![grafik](https://user-images.githubusercontent.com/44204527/109018378-5bbb6580-76b8-11eb-9613-825be0815666.png)

So the operation exists with "200 OK", but the simulation status is "ERROR". There are no helpers to see what went wrong.

### Notes
- It would be great to be able to download the json file instead of trying to catch it in the network view
- The simulation status stays on "PENDING" until one updates the page.

**Comment by smartie2076** [comment]
These are the json files sent to the MVS API:

[simplefied_2.txt](https://github.com/rl-institut/mvs_eland_api/files/6036870/simplefied_2.txt)
[Only_demand_and_provider.txt](https://github.com/rl-institut/mvs_eland_api/files/6036871/Only_demand_and_provider.txt)
[pv_demand_provider.txt](https://github.com/rl-institut/mvs_eland_api/files/6036872/pv_demand_provider.txt)

**Comment by smartie2076** [comment]
### Parsing EPA input file

I added a function in `tests/test_benchmark_scenarios.py`:

```
def help_execute(file):
    with open(os.path.join("EPA", file)) as json_file:
        epa_dict = json.load(json_file)

    dict_values = convert_epa_params_to_mvs(epa_dict)

    dict_values = run_simulation(dict_values, epa_format=False)

    print(dict_values.keys())
    print(dict_values["kpi"])

file_1 = "Only_demand_and_provider.json"
file_2 = "pv_demand_provider.json"
file_3 = "simplefied_2.json"

help_execute(file_1)
```

**Scenario 1: Only_demand_and_provider**
```
WARNING:root:The parameters group 'constraints' is not present in the EPA parameters
to be parsed into MVS json format
WARNING:root:The parameters group 'fixcost' is not present in the EPA parameters to b
e parsed into MVS json format
Traceback (most recent call last):
  File "tests/test_benchmark_scenarios.py", line 363, in <module>
    help_execute()
  File "tests/test_benchmark_scenarios.py", line 359, in help_execute
    dict_values = convert_epa_params_to_mvs(epa_dict)
  File "d:\pycharmprojects\mvs_eland\src\multi_vector_simulator\utils\data_parser.py", line 434, in convert_epa_params_to_mvs
    f"The assets parameters '{MAP_MVS_EPA[asset_group]}' is not present in the EPA parameters to be parsed into MVS json format"
TypeError: 'int' object is not callable
```
The first messages are fine, we are simply updating it with default values. The second is central.

The debug messages are the same in **Scenario 2: pv_demand_provider** and **Scenario 3: simplefied_2**. So, we need to look at `src.utils.data_parser.convert_epa_params_to_mvs()`.

**Comment by smartie2076** [comment]
The problem is that no `energy_storage` (EPA topology, MVS: `energyStorage`) branch is included in the json input file provided by EPA - even in the case where storage is implemented:

![grafik](https://user-images.githubusercontent.com/44204527/109027470-1c454700-76c1-11eb-9781-b384837f9c60.png)

The `logging.info` message did not parse because `logging.INFO` was used:
```
            logging.INFO(
                f"The assets parameters '{MAP_MVS_EPA[asset_group]}' is not present in the EPA parameters to be parsed into MVS json format"
            )
```
Should be 
```
            logging.info(
                f"The assets parameters '{MAP_MVS_EPA[asset_group]}' is not present in the EPA parameters to be parsed into MVS json format"
            )
```

The log then reads:
```
WARNING:root:The parameters group 'constraints' is not present in the EPA parameters to be parsed into MVS json format
WARNING:root:The parameters group 'fixcost' is not present in the EPA parameters to be parsed into MVS json format
Traceback (most recent call last):
  File "tests/test_benchmark_scenarios.py", line 368, in <module>
    help_execute(file_3)
  File "tests/test_benchmark_scenarios.py", line 359, in help_execute
    dict_values = convert_epa_params_to_mvs(epa_dict)
  File "d:\pycharmprojects\mvs_eland\src\multi_vector_simulator\utils\data_parser.py", line 481, in convert_epa_params_to_mvs
    raise (MissingParameterError("\n".join(error_msg)))
multi_vector_simulator.utils.exceptions.MissingParameterError:

The following parameter groups and sub parameters are missing from input parameters:
energyStorage
        `inflow_direction` parameter
        `optimizeCap` parameter
        `outflow_direction` parameter
        `label` parameter
        `type_oemof` parameter
        `energyVector` parameter
```

This is something that needs to be fixed on EPA side.

**Comment by smartie2076** [comment]
Upon further investigation, the EPA always sends only the asset groups that have at least one asset to the MVS. This results in each of the above simulations only being provided a set of asset groups, but not all that the MVS is expecting. This is different from scenario to scenario in the list above. We can fix this by adding empty entries to our dict_values when an asset group is not provided.

**Comment by smartie2076** [comment]
@Bachibouzouk do you think we should fix the EPA parser that way? I know we decided to always require all csv files because this was more explicit, but I guess the EPA avoids human error enough that we can accept this implicitly?

**Comment by Bachibouzouk** [comment]
We can also decide to raise this as a warning and not as an error if this is ok not to have all asset_groups filled?

**Comment by smartie2076** [comment]
> We can also decide to raise this as a warning and not as an error if this is ok not to have all asset_groups filled?

I dont think that the MVS can deal with it. If not in the parser, we need to add the groups in `dict_values `in the MVS.

**Comment by Bachibouzouk** [comment]
> I dont think that the MVS can deal with it. If not in the parser, we need to add the groups in `dict_values `in the MVS.

In that case the parser is the right place to do this :)
