### ISSUE TITLE
MVS fails with EPA inputs - missing key "dispatchable"

### ISSUE THREAD

**Issue by smartie2076** [rl-institut/mvs_eland_api#11]
One of the scenarios in `martha.hoffmann` on the EPA online version is the "Warehouse 14" scenario. It terminates with status ERROR. 

MVS json request file send from EPA: 
[warehouse_14.txt](https://github.com/rl-institut/mvs_eland_api/files/6037343/warehouse_14.txt)

The file can be parsed and initiates the simulation, but one key seems to be missing:

```
Traceback (most recent call last):
  File "tests/test_benchmark_scenarios.py", line 369, in <module>
    help_execute(file_4)
  File "tests/test_benchmark_scenarios.py", line 361, in help_execute
    run_simulation(dict_values)
  File "d:\pycharmprojects\mvs_eland\src\multi_vector_simulator\server.py", line 95, in run_simulation
    C0.all(dict_values)
  File "d:\pycharmprojects\mvs_eland\src\multi_vector_simulator\C0_data_processing.py", line 78, in all
    C1.check_feedin_tariff_vs_levelized_cost_of_generation_of_production(dict_values)
  File "d:\pycharmprojects\mvs_eland\src\multi_vector_simulator\C1_verification.py", line 189, in check_feedin_tariff_vs_levelized_cost_of_generation_of_production
    dict_values[ENERGY_PRODUCTION][production_asset][DISPATCHABILITY]
KeyError: 'dispatchable'
```
No keys are indicated to be missing, so I suppose that the issue is within the MVS. It may have to do with some decisions in `C0`, where dispatchablility might have been attibuted depending on whether or not a `file_name` was provided for the timeseries.

**Comment by smartie2076** [comment]
I actually found that the key `dispatchable` is attributed to the storage subassets in the EPA. I would not know why this would be necessary, maybe it was a communication issue?

We do need to fix the above in `C0` for json input files, but on the other hand, the EPA can easily provide the key when defining non-dispatchable sources, no pre-processing needed.

**Comment by Bachibouzouk** [comment]
![Screenshot_2021-02-24_19-23-54](https://user-images.githubusercontent.com/4399407/109047493-3b9a9f00-76d6-11eb-9c32-c73406ef1cee.png)

Now you can see the mvs token in the log of the browser and click use it to visit mvs-eland.rl-institut.de/check/<token>

**Comment by smartie2076** [comment]
Oh, nice! Thank you for implementing it!
